server:
  port: 5050
spring:
  datasource:
    driver-class: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/testc
    username: root


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    #smtp mail properties
  mail:
    host: smtp.gmail.com
    port: 587
    username: mymail@gmail.com
    password: password
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com



